--- 
Disc: 
- iso
- img
Executable: 
- exe
- bat
- jar
Video: 
- avi
- wmv
- mp4
- mov
- mkv
- 3gp
- ogv
- mpg
- flv
Sound: 
- wav
- wma
- ac3
- mp3
- ogg
- flac
Archive: 
- rar
- 7z
- zip
- tar
- gz
- ace
Image: 
- jpg
- gif
- jpeg
- png
- bmp
- xcf
- ico
Document: 
- rtf
- txt
- doc
- docx
- odt
- pdf
Other: []
